name: 'Show file'
description: 'Shows file contents'

inputs:
  file_path:
    description: 'The path of the file to be shown'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Show file
    shell: bash
    run: cat ${{ inputs.file_path }}
